name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:

    # Checkout branch
    - name: Checkout branch
      uses: actions/checkout@v4

    # Commit the source files to GitHub Pages branch
    - name: Commit files to GitHub Pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: src
